### ISSUE TITLE
I was looking to do this for my own sublime settings but I have a question!

### ISSUE THREAD

**Issue by reidcooper** [mrmartineau/SublimeText3UserSettings#1]
I was looking to back up my sublime text 3 settings to github just like you, however I was curious on what I had to back up. 

In my repo, I also backed up the Installed Packages Folder, should that pushed up as well or ignored? 

To the same question, does the Package Control.sublime-settings automatically install the packages if found in a fresh install of sublime text 3?

Thanks!

**Comment by mrmartineau** [comment]
@reidcooper Package Control is not installed when Sublime is installed. you will need to go to packagecontrol.io and follow the install instructions. Only then will it install the packages listed in the `Package Control.sublime-settings` file.

I wouldn't worry about the `Installed Packages` folder because Package Control will always be changing it.

Have a look at https://packagecontrol.io/docs/syncing to find out more about syncing your prefs
